### ISSUE TITLE
Imagecodecs for full support

### ISSUE THREAD

**Issue by Czaki** [conda-forge/tifffile-feedstock#36]
I'm not familiar with conda build system, but I think that it will be good to tifffile depends on imagecodecs, not imagecodecs-lite. 

I found way to build Imagecodecs on linux and macos for the purpose of creating wheel: https://github.com/Czaki/imagecodecs

All scripts needed are in `build_utils` 

I can support someone who would like to create such formula, or can try to create it on my own, if got some good tutorial.

**Comment by ocefpaf** [comment]
If we can make that a conda-recipe it would be awesome. I tried in https://github.com/conda-forge/staged-recipes/pull/10203 but gave up. There is also an older attempt in https://github.com/conda-forge/staged-recipes/pull/6842. However, our best bet would probably be https://github.com/conda-forge/staged-recipes/pull/10331. Can you take a look at that PR and share you experiences there?

**Comment by Czaki** [comment]
I try ma best. I have hope that maintainer will be interested or my information somehow speedup process.
