### ISSUE TITLE
Upgrade to 2020.2.16 broke LZW compressed TIFF support

### ISSUE THREAD

**Issue by kmilos** [conda-forge/tifffile-feedstock#39]
Since the new version depends on full imagecodecs and removed internal lzw_decode, the workaround to depend on imagecodecs-lite no longer works and functionality is lost.

**Comment by ocefpaf** [comment]
> Since the new version depends on full imagecodecs and removed internal lzw_decode, the workaround to depend on imagecodecs-lite no longer works and functionality is lost.

Yep. Unless someone works on a full `imagecodecs` package our options are to downgrade or loose that functionality. Note also that `imagecodecs-lite` is outdated due to https://github.com/conda-forge/imagecodecs-lite-feedstock/issues/4.

**Comment by kmilos** [comment]
> our options are to downgrade or loose that functionality

IMHO dropping functionality without warning the user is not really a good option

**Comment by ocefpaf** [comment]
> IMHO dropping functionality without warning the user is not really a good option

I agree. We never had the full imagecodecs and we never tested for the full functionalities that may be missing. So, in a way, we never dropped b/c we never announced a full featured package.

**Comment by ericpre** [comment]
This should be working with the last build, @kmilos can you confirm?

**Comment by kmilos** [comment]
Confirmed working now on a LZW compressed TIFF, thanks @ericpre
